
import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import PageLayout from "@/components/PageLayout";
import Button from "@/components/Button";
import { Button as UIButton } from "@/components/ui/button";
import CheckboxWithLabel from "@/components/CheckboxWithLabel";
import { useToast } from "@/hooks/use-toast";
import { useMinimumReadTime } from "@/hooks/useMinimumReadTime";

const HowRouteWorks = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { currentUser, updateUserData, isLoading } = useAuth();
  const { toast } = useToast();

  const [policyUnderstood, setPolicyUnderstood] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isWithdrawing, setIsWithdrawing] = useState(false);
  const { canProceed, timeRemaining } = useMinimumReadTime(30);

  // Load existing confirmation status
  useEffect(() => {
    if (currentUser?.routesPolicyAcknowledged) {
      setPolicyUnderstood(true);
    }
  }, [currentUser]);

  const handleContinue = async () => {
    if (!policyUnderstood) {
      toast({
        title: "Confirmation Required",
        description: "Please acknowledge that you understand the policy.",
        variant: "destructive",
      });
      return;
    }

    setIsSaving(true);
    try {
      const success = await updateUserData({
        routesPolicyAcknowledged: true,
        routesPolicyAcknowledgedAt: new Date().toISOString(),
        step: 'routes_policy'
      });

      if (success) {
        // If user came from summary, return to summary instead of continuing flow
        if (searchParams.get('from') === 'summary') {
          navigate("/acknowledgements-summary");
        } else {
          navigate("/cancellation-policy");
        }
      }
    } catch (error) {
      console.error("Error saving routes policy acknowledgment:", error);
      toast({
        title: "Save Failed",
        description: "Unable to save acknowledgment. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleWithdraw = async () => {
    setIsWithdrawing(true);
    try {
      const success = await updateUserData({
        status: 'withdrawn',
        withdrawnAt: new Date().toISOString(),
        withdrawalReason: 'Not satisfied with route policy',
        step: 'routes_policy'
      });

      if (success) {
        navigate("/thank-you");
      } else {
        toast({
          title: "Withdrawal Failed",
          description: "Unable to process withdrawal. Please try again.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Error withdrawing application:", error);
      toast({
        title: "Withdrawal Failed",
        description: "Unable to process withdrawal. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsWithdrawing(false);
    }
  };

  return (
    <PageLayout compact title="">
      <div className="w-full flex flex-col items-center">
        <h2 className="text-center text-3xl font-bold mb-6 animate-slide-down">
          How Route Works
        </h2>
        
        <div className="w-full max-w-md animate-fade-in">
          <div className="bg-gray-50 border border-gray-300 rounded-lg p-4 max-h-[500px] overflow-y-auto mb-6">
            <div className="text-left space-y-4 text-sm text-gray-900">
              <p>
                Please note that routes are generated by our automated system, which considers several factors such as live traffic conditions, the time required to find parking, and the estimated time needed to meet the customer and complete each task. Based on these parameters, the system calculates the estimated time of arrival (ETA) for completing the route.
              </p>
              
              <p>
                As Laundryheap operates as an on-demand service, new orders may be assigned to you while you are already on your route. These additional tasks are automatically planned to fit within your booked block time. Therefore, you will not have the option to decline any tasks added to your route.
              </p>
            </div>
          </div>
          
          {searchParams.get('from') !== 'summary' && (
            <CheckboxWithLabel
              label="I understand the policy"
              checked={policyUnderstood}
              onChange={setPolicyUnderstood}
            />
          )}
        </div>
        
        {searchParams.get('from') !== 'summary' && !canProceed && (
          <div className="w-full max-w-md text-center mt-4">
            <p className="text-sm text-muted-foreground">
              Please read the routes policy carefully. You can continue in {timeRemaining} second{timeRemaining !== 1 ? 's' : ''}.
            </p>
          </div>
        )}
        
        <div className="w-full flex flex-col items-center space-y-4 mt-6">
          {searchParams.get('from') === 'summary' ? (
            <UIButton
              onClick={() => navigate("/acknowledgements-summary")}
              className="w-full max-w-xs"
              variant="outline"
              disabled={isSaving || isLoading}
            >
              Back to Summary
            </UIButton>
          ) : (
            <>
              <Button
                onClick={handleContinue}
                className="w-full max-w-xs"
                disabled={isSaving || isLoading || !canProceed}
              >
                {isSaving ? "Saving..." : "Continue"}
              </Button>

              <Button
                onClick={handleWithdraw}
                className=" text-white w-full max-w-xs bg-laundryheap-Red hover:bg-opacity-90"
                disabled={isSaving || isLoading || isWithdrawing}
                showArrow={false}
              >
                {isWithdrawing ? "Processing..." : "Withdraw my Application"}
              </Button>
            </>
          )}
        </div>
      </div>
    </PageLayout>
  );
};

export default HowRouteWorks;

